import React from 'react';
import NoiseImage from '../../assets/Noise.webp';

export default function App() {
  return (
    <div className="min-h-screen text-stone-100 p-6 md:p-12 font-sans tracking-tight bg-stone-900" style={{ fontFamily: '"Roboto Condensed", sans-serif' }}>
       {/* Add Google Font link dynamically */}
      <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet" />
      
      <div className="max-w-5xl mx-auto">
        {/* Header Section */}
        <header className="flex flex-col md:flex-row md:items-center justify-between border-b border-stone-700 pb-4 mb-6">
          <h1 className="text-4xl md:text-5xl font-light mb-4 md:mb-0">
            Noise
          </h1>

          
        </header>

        {/* Main Content Layout */}
        <div className="block">
            
            {/* Right Floated Image Card */}
            <div className="float-right w-72 ml-6 mb-4 bg-stone-800 border border-stone-700 shadow-xl">
                {/* Card Title */}
                <div className="bg-stone-900 text-white text-center font-bold py-2 border-b border-stone-700 font-sans tracking-wide">
                    Noise
                </div>
                
                {/* Image Container */}
                <div className="relative group">
                    <img 
                        src={NoiseImage} 
                        alt="Noise Indicator HUD" 
                        className="w-[268.4px] h-[277.93px] object-cover block opacity-90 hover:opacity-100 transition-opacity"
                    />
                    {/* Gallery Icon overlay */}
                    <div className="absolute bottom-2 right-2 bg-black/60 p-1 rounded hover:bg-black/80 cursor-pointer">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                    </div>
                </div>
            </div>

            {/* Intro Text */}
            <div className="mb-8 text-stone-300 font-sans text-[16px] leading-relaxed space-y-4">
                <p>
                    Making <strong className="text-white">noise</strong> may alert animals to the players presence. Noise will be generated by moving or shooting. The faster the player moves, the more noise is produced. Moving through foliage will also make more noise than moving through open terrain.
                </p>
                <p>
                    Noise is indicated by the speaker icon in the lower righthand corner of the HUD. The more bars there are, the more noise is produced. After all bars are visible, further noise increase is indicated by tinting the respective noise bar red. The loudest noise in the game is produced by the <a href="#" className="text-green-400 hover:underline">Saber 4x4</a> with all bars visible in red. Shooting will also produce noise and alarm surrounding animals, but is not shown by the indicator.
                </p>
                <p>
                    Noise can be masked by environmental sounds such as wind and rainfall. This can be further increased by <a href="#" className="text-green-400 hover:underline">Skills</a>.
                </p>
            </div>

            {/* Subheader (Content not provided in screenshot, but header is visible) */}
            <div className="clear-both">
               <div className="flex items-center space-x-2 border-b border-stone-700 pb-2 mb-4">
                    <h2 className="text-2xl font-bold text-green-400">Movement Speed and Noise created</h2>
                </div>
                {/* Placeholder for future table content */}
            </div>

        </div>

        <div className="h-32"></div>
      </div>
    </div>
  );
}