import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ammoPath = path.resolve(__dirname, '../src/data/ammunition.js');

const canonical = {
  ".22LR_Truncated_Cone": { value:250, weight:0.01, stats:{range:'100 m', penetration:1, expansion:17, class:'1'}},
  ".22H_Polymer-Tip": { value:300, weight:0.05, stats:{range:'150 m', penetration:15, expansion:3, class:'1-2'}},
  ".22-250_Polymer-Tip_Bullet": { value:375, weight:0.01, stats:{range:'150 m', penetration:25, expansion:3, class:'2-4'}},
  ".223_Polymer-Tip_Bullet": { value:350, weight:0.01, stats:{range:'150 m', penetration:20, expansion:3, class:'2-4'}},
  ".243_Polymer-Tip": { value:530, weight:0.02, stats:{range:'150 m', penetration:30, expansion:4, class:'2-6'}},
  ".270_Polymer-Tip_Bullet": { value:700, weight:0.03, stats:{range:'150 m', penetration:35, expansion:5, class:'4-8'}},
  ".30-06_Polymer-Tip": { value:850, weight:0.03, stats:{range:'150 m', penetration:45, expansion:13, class:'4-8'}},
  ".30-30_Soft-Point_Round_Nose": { value:220, weight:0.02, stats:{range:'75 m', penetration:35, expansion:4, class:'2-6'}},
  ".300_Magnum_Polymer-Tip": { value:950, weight:0.03, stats:{range:'150 m', penetration:42, expansion:14, class:'7-9'}},
  ".303_British_Polymer-Tip": { value:880, weight:0.04, stats:{range:'150 m', penetration:40, expansion:12, class:'4-8'}},
  ".308_Polymer-Tip_Bullet": { value:850, weight:0.03, stats:{range:'150 m', penetration:44, expansion:13, class:'4-8'}},
  ".338_Mag_Polymer-Tip": { value:1050, weight:0.05, stats:{range:'150 m', penetration:45, expansion:16, class:'7-9'}},
  ".45-70_Soft-Point_Flat_Nose": { value:390, weight:0.03, stats:{range:'75 m', penetration:40, expansion:6, class:'4-9'}},
  ".470_Nitro_Express_FMJ": { value:2660, weight:0.03, stats:{range:'75 m', penetration:100, expansion:23, class:'9'}},
  ".470_Nitro_Express_Soft-Point": { value:2000, weight:0.03, stats:{range:'75 m', penetration:25, expansion:100, class:'9'}},
  ".50_Ball_Minié": { value:450, weight:0.01, stats:{range:'200 m', penetration:40, expansion:30, class:'4-8'}},
  ".50_Ball_Round": { value:300, weight:0.01, stats:{range:'100 m', penetration:30, expansion:30, class:'3-7'}},
  ".50_Polymer-Tip_Sabot": { value:500, weight:0.01, stats:{range:'200 m', penetration:42, expansion:20, class:'4-8'}},
  ".50_Hollow-Point_Sabot": { value:450, weight:0.01, stats:{range:'200 m', penetration:20, expansion:60, class:'4-8'}},
  "6.5mm_Polymer-Tip": { value:650, weight:0.03, stats:{range:'200 m', penetration:40, expansion:4, class:'4-8'}},
  "7.62x35mm_Polymer-Tip": { value:530, weight:0.01, stats:{range:'150 m', penetration:32, expansion:7, class:'3-6'}},
  "7.62x39mm_Polymer-Tip": { value:300, weight:0.01, stats:{range:'150 m', penetration:34, expansion:5, class:'2-6'}},
  "7.62x54R_Soft-Point": { value:380, weight:0.01, stats:{range:'150 m', penetration:15, expansion:17, class:'3-7'}},
  "7mm_Mag_Polymer-Tip": { value:880, weight:0.04, stats:{range:'150 m', penetration:40, expansion:12, class:'4-9'}},
  "9.3x74R_Polymer-Tip": { value:880, weight:0.01, stats:{range:'150 m', penetration:40, expansion:12, class:'5-9'}}
};

(async function(){
  try {
    const imported = await import(`file://${ammoPath}`);
    const ammo = imported.default || imported.ammo || imported;
    if (!Array.isArray(ammo)) throw new Error('ammo not array');

    let updated = 0;
    for (const a of ammo) {
      if (canonical[a.id]) {
        const c = canonical[a.id];
        a.value = c.value;
        a.weight = c.weight;
        a.stats = Object.assign({}, a.stats || {}, c.stats);
        updated++;
      }
    }

    const out = `// Auto-generated ammunition file (normalized)
// Generated by tools/canonicalizeRifleStats.mjs

const ammunition = ${JSON.stringify(ammo, null, 2)};

export const ammo = ammunition;
export default ammunition;
`;
    fs.writeFileSync(ammoPath, out, 'utf8');
    console.log('Canonicalized', updated, 'rifle ammo entries.');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
