import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ammoPath = path.resolve(__dirname, '../src/data/ammunition.js');

const canonical = {
  "300_gr._Small_Game_Point_Arrow": { value:530, weight:0.06, stats:{range:'20 m', penetration:10, expansion:0, class:'1-2'}},
  "350_Grain_Broadhead_Traditional_Arrow": { value:500, weight:0.07, stats:{range:'20 m', penetration:15, expansion:0, class:'1-3'}},
  "420_gr._Broadhead_Arrow": { value:700, weight:0.07, stats:{range:'50 m', penetration:50, expansion:0, class:'2-7'}},
  "600_gr._Broadhead_Arrow": { value:880, weight:0.08, stats:{range:'90 m', penetration:90, expansion:0, class:'7-9'}},
  "540_Grain_Broadhead": { value:750, weight:0.08, stats:{range:'75 m', penetration:75, expansion:0, class:'4-7'}},
  "700_Grain_Broadhead": { value:900, weight:0.09, stats:{range:'90 m', penetration:90, expansion:0, class:'8-9'}},
  "300_gr._Small_Game_Point_Bolt": { value:600, weight:0.06, stats:{range:'30 m', penetration:10, expansion:0, class:'1-2'}},
  "420_gr._Broadhead_Bolt": { value:770, weight:0.07, stats:{range:'50 m', penetration:50, expansion:0, class:'2-7'}},
  "600_gr._Broadhead_Bolt": { value:950, weight:0.08, stats:{range:'90 m', penetration:90, expansion:0, class:'7-9'}}
};

(async function(){
  try {
    const imported = await import(`file://${ammoPath}`);
    const ammo = imported.default || imported.ammo || imported;
    if (!Array.isArray(ammo)) throw new Error('ammo not array');

    let updated = 0;
    for (const a of ammo) {
      if (canonical[a.id]) {
        const c = canonical[a.id];
        a.value = c.value;
        a.weight = c.weight;
        a.stats = Object.assign({}, a.stats || {}, c.stats);
        updated++;
      }
    }

    const out = `// Auto-generated ammunition file (normalized)
// Generated by tools/canonicalizeArrowsBolts.mjs

const ammunition = ${JSON.stringify(ammo, null, 2)};

export const ammo = ammunition;
export default ammunition;
`;
    fs.writeFileSync(ammoPath, out, 'utf8');
    console.log('Canonicalized', updated, 'arrow/bolt ammo entries.');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
