import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ammoPath = path.resolve(__dirname, '../src/data/ammunition.js');

const canonical = {
  "12_GA_Slug": { value:880, weight:0.05, stats:{range:'50 m', penetration:40, expansion:19, class:'4-8'}},
  "12_GA_Birdshot": { value:180, weight:0.05, stats:{range:'25 m', penetration:0, expansion:0, class:'1'}},
  "12_GA_Buckshot": { value:530, weight:0.05, stats:{range:'25 m', penetration:5, expansion:0, class:'2-5'}},
  "20_GA_Slug": { value:800, weight:0.05, stats:{range:'50 m', penetration:33, expansion:16, class:'4-7'}},
  "20_GA_Birdshot": { value:150, weight:0.05, stats:{range:'25 m', penetration:0, expansion:0, class:'1'}},
  "20_GA_Buckshot": { value:500, weight:0.05, stats:{range:'25 m', penetration:4, expansion:0, class:'2-5'}},
  "16_GA_Slug": { value:880, weight:0.05, stats:{range:'50 m', penetration:37, expansion:16, class:'4-7'}},
  "16_GA_Birdshot": { value:180, weight:0.05, stats:{range:'25 m', penetration:0, expansion:0, class:'1'}},
  "16_GA_Buckshot": { value:530, weight:0.05, stats:{range:'25 m', penetration:5, expansion:0, class:'4-7'}},
  "10_GA_Plastic_Birdshot": { value:200, weight:0.05, stats:{range:'25 m', penetration:0, expansion:0, class:'1-2'}},
  "10_GA_Brass_Birdshot": { value:200, weight:0.05, stats:{range:'25 m', penetration:0, expansion:0, class:'1-2'}},
  "10_GA_Brass_Buckshot": { value:600, weight:0.05, stats:{range:'25 m', penetration:5, expansion:0, class:'4-7'}},
  "10_GA_Plastic_Buckshot": { value:600, weight:0.05, stats:{range:'25 m', penetration:5, expansion:0, class:'4-7'}},
  "10_GA_Brass_Slug": { value:950, weight:0.05, stats:{range:'50 m', penetration:45, expansion:22, class:'6-9'}},
  "10_GA_Plastic_Slug": { value:950, weight:0.05, stats:{range:'50 m', penetration:45, expansion:22, class:'6-9'}},
  ".410_Birdshot": { value:200, weight:0.05, stats:{range:'25 m', penetration:0, expansion:0, class:'1'}},
  ".410_Buckshot": { value:500, weight:0.05, stats:{range:'25 m', penetration:4, expansion:0, class:'2-4'}},
  ".410_Slug": { value:800, weight:0.05, stats:{range:'50 m', penetration:33, expansion:16, class:'4-7'}}
};

(async function(){
  try {
    const imported = await import(`file://${ammoPath}`);
    const ammo = imported.default || imported.ammo || imported;
    if (!Array.isArray(ammo)) throw new Error('ammo not array');

    let updated = 0;
    for (const a of ammo) {
      if (canonical[a.id]) {
        const c = canonical[a.id];
        a.value = c.value;
        a.weight = c.weight;
        a.stats = Object.assign({}, a.stats || {}, c.stats);
        updated++;
      }
    }

    const out = `// Auto-generated ammunition file (normalized)
// Generated by tools/canonicalizeShotgunStats.mjs

const ammunition = ${JSON.stringify(ammo, null, 2)};

export const ammo = ammunition;
export default ammunition;
`;
    fs.writeFileSync(ammoPath, out, 'utf8');
    console.log('Canonicalized', updated, 'shotgun ammo entries.');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
