import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ammoPath = path.resolve(__dirname, '../src/data/ammunition.js');

const canonical = {
  ".357_Flat_Nose_Hard-Cast": { value:350, weight:0.01, stats:{range:'50 m', penetration:50, expansion:4, class:'2-6'}},
  ".44_Flat_Nose_Hard-Cast": { value:530, weight:0.02, stats:{range:'50 m', penetration:70, expansion:16, class:'3-8'}},
  "10mm_Auto_Hard_Cast": { value:280, weight:0.01, stats:{range:'50 m', penetration:50, expansion:8, class:'2-6'}},
  ".357_Jacketed_Hollow-Point": { value:220, weight:0.01, stats:{range:'50 m', penetration:12, expansion:18, class:'2-6'}},
  ".44_Jacketed_Hollow-Point": { value:260, weight:0.02, stats:{range:'50 m', penetration:17, expansion:70, class:'3-8'}},
  ".45_Colt_FMJ": { value:600, weight:0.03, stats:{range:'50 m', penetration:55, expansion:6, class:'2-5'}},
  ".45_Colt_Flat_Nose_Hard-Cast": { value:530, weight:0.02, stats:{range:'50 m', penetration:17, expansion:70, class:'2-5'}},
  ".454_Jacketed_Hollow-Point": { value:440, weight:0.03, stats:{range:'50 m', penetration:25, expansion:100, class:'4-9'}},
  ".454_Flat_Nose_Hard-Cast": { value:770, weight:0.03, stats:{range:'50 m', penetration:100, expansion:23, class:'4-9'}},
  "10mm_Auto_Jacketed_Hollow-Point": { value:350, weight:0.01, stats:{range:'50 m', penetration:12, expansion:36, class:'2-6'}}
};

(async function(){
  try {
    const imported = await import(`file://${ammoPath}`);
    const ammo = imported.default || imported.ammo || imported;
    if (!Array.isArray(ammo)) throw new Error('ammo not array');

    let updated = 0;
    for (const a of ammo) {
      if (canonical[a.id]) {
        const c = canonical[a.id];
        a.value = c.value;
        a.weight = c.weight;
        a.stats = Object.assign({}, a.stats || {}, c.stats);
        updated++;
      }
    }

    const out = `// Auto-generated ammunition file (normalized)
// Generated by tools/canonicalizeHandgunStats.mjs

const ammunition = ${JSON.stringify(ammo, null, 2)};

export const ammo = ammunition;
export default ammunition;
`;
    fs.writeFileSync(ammoPath, out, 'utf8');
    console.log('Canonicalized', updated, 'handgun ammo entries.');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
