import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ammoPath = path.resolve(__dirname, '../src/data/ammunition.js');

function classifyList(ammo){
  const byCategory = { Rifle: [], Shotgun: [], Handgun: [], Bow: [], Other: [] };

  for (const a of ammo){
    const cat = (a.category || '').toLowerCase();
    const id = (a.id || '').toLowerCase();
    const type = (a.type || '').toLowerCase();

    if (type.includes('bird') || id.includes('bird') || id.includes('birdshot')) {
      byCategory.Shotgun.push(a);
      continue;
    }

    if (cat.includes('shot') || id.includes('buck') || id.includes('slug')) {
      byCategory.Shotgun.push(a);
    } else if (cat.includes('rifle') || id.includes('rifle') || id.match(/\b\d{2,3}\b/)) {
      byCategory.Rifle.push(a);
    } else if (cat.includes('hand') || id.includes('hand') || id.includes('.22') || id.includes('.45') || id.includes('.50')) {
      byCategory.Handgun.push(a);
    } else if (cat.includes('bow') || id.includes('broadhead') || id.includes('arrow')) {
      byCategory.Bow.push(a);
    } else {
      byCategory.Other.push(a);
    }
  }

  return byCategory;
}

(async function main(){
  const imported = await import(`file://${ammoPath}`);
  const ammo = imported.default || imported.ammo || imported;
  if (!Array.isArray(ammo)) throw new Error('ammo is not an array');

  const byCategory = classifyList(ammo);

  function printGroup(name, list){
    console.log(`\n=== ${name} (${list.length}) ===`);
    for (const a of list){
      console.log(`${a.id} — ${a.name}`);
    }
  }

  console.log('Ammunition Classification Report');
  console.log('Generated by tools/reportAmmoClassification.mjs');

  printGroup('Rifle', byCategory.Rifle);
  printGroup('Shotgun', byCategory.Shotgun);
  printGroup('Handgun', byCategory.Handgun);
  printGroup('Bow', byCategory.Bow);
  printGroup('Other', byCategory.Other);

  console.log('\nSummary:');
  console.log(`Rifle: ${byCategory.Rifle.length}`);
  console.log(`Shotgun: ${byCategory.Shotgun.length}`);
  console.log(`Handgun: ${byCategory.Handgun.length}`);
  console.log(`Bow: ${byCategory.Bow.length}`);
  console.log(`Other: ${byCategory.Other.length}`);
})();
